name: habitzen
description: A cross-platform habit tracker with Firebase sync, streaks, charts, and motivational quotes.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  provider: ^6.1.2
  firebase_analytics: ^11.0.0
  uuid: ^4.5.1
  shared_preferences: ^2.3.2
  http: ^1.2.2
  shimmer: ^3.0.0
  intl: ^0.19.0
  fl_chart: ^0.69.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/terms.md
